
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nishant
 */
public class signin extends javax.swing.JFrame {

    public signin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 50));

        jLabel1.setText("SIGNIN");

        jLabel2.setText("7 DIGIT ACCOUNT NUMBER");

        jLabel3.setText("4 DIGIT PIN");

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet rs = null;
        long accountnumber = 0;
        int password = 0;
        int permission = 0;
        String accnum = jTextField1.getText();
        String pin = jPasswordField1.getText();
        try {
            accountnumber = Long.parseLong(accnum);
            if (accnum.length() > 7 || accnum.length() < 7) {
                JOptionPane.showMessageDialog(this, "Enter 7 digit AccountNumber only");
            }
            jTextField1.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Account Number must be in numbers");
        }
        try {
            password = Integer.parseInt(pin);
            if (pin.length() > 4 || pin.length() < 4) {
                JOptionPane.showMessageDialog(this, "Enter 4 digit Password only");
            }
            jPasswordField1.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Password must be in numbers");
        }
        if (!(accnum.length() > 7 || accnum.length() < 7) && !(pin.length() > 4 || pin.length() < 4)) {
            permission = 1;
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bankdatabase", "root", "");
            Statement stmt = con.createStatement();
            String query = "select * from customers where account_number=" + accountnumber + " and password=" + password + ";";
            rs = stmt.executeQuery(query);
            if (rs.next()) {
                signinyes sy = new signinyes(rs);
                sy.setVisible(true);
                dispose();
            } else {
                if (permission == 1) {
                    JOptionPane.showMessageDialog(this, "Account Number or password incorrect");
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

        /*else if (accountnumber == acc.account_number) {
                if ( == acc.password) {
                    
                } else {
                    JOptionPane.showMessageDialog(this,"Account Number and Password Not matching");
                    
                }
            } else if (pin.length() < 4 || pin.length() > 4) {
                System.out.println("Enter correct 4 digit pin");
                
            }*/
 /*if (found == 0) {
            JOptionPane.showMessageDialog(this,"Account Not Found");
        }
        jTextField1.setText("");
        jPasswordField1.setText("");}
        catch(Exception e){JOptionPane.showMessageDialog(this,"Account Number and Password must be numbers");
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    ResultSet rs = null;
        long accountnumber = 0;
        int password = 0;
        int permission = 0;
        String accnum = jTextField1.getText();
        String pin = jPasswordField1.getText();
        try {
            accountnumber = Long.parseLong(accnum);
            if (accnum.length() > 7 || accnum.length() < 7) {
                JOptionPane.showMessageDialog(this, "Enter 7 digit AccountNumber only");
            }
            jTextField1.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Account Number must be in numbers");
        }
        try {
            password = Integer.parseInt(pin);
            if (pin.length() > 4 || pin.length() < 4) {
                JOptionPane.showMessageDialog(this, "Enter 4 digit Password only");
            }
            jPasswordField1.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Password must be in numbers");
        }
        if (!(accnum.length() > 7 || accnum.length() < 7) && !(pin.length() > 4 || pin.length() < 4)) {
            permission = 1;
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bankdatabase", "root", "");
            Statement stmt = con.createStatement();
            String query = "select * from customers where account_number=" + accountnumber + " and password=" + password + ";";
            rs = stmt.executeQuery(query);
            if (rs.next()) {
                signinyes sy = new signinyes(rs);
                sy.setVisible(true);
                dispose();
            } else {
                if (permission == 1) {
                    JOptionPane.showMessageDialog(this, "Account Number or password incorrect");
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Connection Unsuccessful");
        }
}
    }//GEN-LAST:event_jPasswordField1KeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void signedinuser(String customer_name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void sinuser(String customer_name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
