
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nishant
 */
public class signup extends javax.swing.JFrame {

    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 50));

        jLabel1.setText("NAME");

        jLabel2.setText("7 DIGIT ACCOUNT NUMBER");

        jLabel3.setText("4 DIGIT PIN");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("SIGNUP");

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton1)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        /* String n = jTextField1.getText();
                String p = jPasswordField1.getText();
                String c = jTextField2.getText();
                if(n.length()>7||n.length()<7) System.out.println("Enter 7 digit account number");
                else if(p.length()>4||p.length()<4) System.out.println("Enter 4 digit password");
                else
                {
                    //double account_number = Long.parseLong(n);
                    //int password=Integer.parseInt(p);
                }*/
        Statement stmt = null;
        Connection con = null;
        long accountnumber = 0;
        int password = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankdatabase", "root", "");
            stmt = con.createStatement();

            String n = jTextField2.getText();
            try {
                accountnumber = Long.parseLong(n);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Enter account number in numbers only");
            }
            String p = jPasswordField1.getText();
            try {
                password = Integer.parseInt(p);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Enter password in numbers only");
            }
            String c = jTextField1.getText();
            if (n.length() > 7 || n.length() < 7) {
                JOptionPane.showMessageDialog(this, "Not valid account number");
            } else if (p.length() < 4 || p.length() > 4) {
                JOptionPane.showMessageDialog(this, "Enter correct 4 digit pin");
            } else {
                //customers.add(new Account(accountnumber,password,c));
                String query = "insert into customers values('" + c + "'," + accountnumber + "," + password + "," + 0 + ");";
                stmt.execute(query);
                con.close();
                JOptionPane.showMessageDialog(this, "Account creation successful");
                dispose();
            }
            jTextField1.setText("");
            jTextField2.setText("");
            jPasswordField1.setText("");//}catch(Exception e){JOptionPane.showMessageDialog(this, "Account Number and Password must be numbers");}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "DataBase connection unsuccessful");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Statement stmt = null;
            Connection con = null;
            long accountnumber = 0;
            int password = 0;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankdatabase", "root", "");
                stmt = con.createStatement();

                String n = jTextField2.getText();
                try {
                    accountnumber = Long.parseLong(n);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Enter account number in numbers only");
                }
                String p = jPasswordField1.getText();
                try {
                    password = Integer.parseInt(p);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Enter password in numbers only");
                }
                String c = jTextField1.getText();
                if (n.length() > 7 || n.length() < 7) {
                    JOptionPane.showMessageDialog(this, "Not valid account number");
                } else if (p.length() < 4 || p.length() > 4) {
                    JOptionPane.showMessageDialog(this, "Enter correct 4 digit pin");
                } else {
                    //customers.add(new Account(accountnumber,password,c));
                    String query = "insert into customers values('" + c + "'," + accountnumber + "," + password + "," + 0 + ");";
                    stmt.execute(query);
                    con.close();
                    JOptionPane.showMessageDialog(this, "Account creation successful");
                    dispose();
                }
                jTextField1.setText("");
                jTextField2.setText("");
                jPasswordField1.setText("");//}catch(Exception e){JOptionPane.showMessageDialog(this, "Account Number and Password must be numbers");}
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "DataBase connection unsuccessful");
            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
